dataCallback({
    conditions: [
        "wer zuletzt auf einem Konzert war",
        "wer zuletzt aus dem Urlaub zurückkam",
        "wer die höchste Hausnummer hat",
        "wer zuletzt seine Eltern besucht hat",
        "wer die meisten Schlüssel am Schlüsselbund hat",
        "wer die meisten Brettspiele hat",
        "wer die meisten Kleidungsstücke trägt",
        "wer die höchste Zahl in den letzten 4 Ziffern der Handynummer hat",
        "wessen Arbeitsweg am längsten ist",
        "wer zuletzt Fahrrad gefahren ist",
        "wer zuletzt Suppe gegessen hat",
        "wer die meisten Buchstaben im Vor- und Nachnamen hat",
        "wessen Anfangsbuchstabe des Vornamens im Alphabet als letztes kommt",
        "wer zuletzt Alkohol getrunken hat",
        "wer die höchste Postleitzahl hat",
        "wer die meisten Länder bereist hat",
        "wer letzte Nacht am wenigsten geschlafen hat",
        "wer zuletzt mit seiner Mutter gesprochen hat",
        "wer das größte Handy hat",
        "wer am kleinsten ist",
        "wer die größten Hände hat",
        "wer am ältesten ist",
        "wer als nächstes Geburtstag hat",
        "wer die meisten 6en in seiner Handynummer hat",
        "wer am frühesten aufgestanden ist",
        "wer zuletzt einen Mord im Fernsehen gesehen hat",
        "wer die meisten Münzen im Portemonnaie hat",
        "wer zuletzt etwas geliked oder kommentiert hat",
        "wer zuletzt die Batterien im Rauchmelder gewechselt hat",
        "wer als letztes angekommen ist",
        "wer am meisten Akku beim Handy hat",
        "wer zuletzt etwas gespendet hat",
        "wer schwarze Socken und gleichzeitig eine schwarze Unterhose trägt",
        "wer die längste Haftstrafe hinter sich hat",
        "wer zuletzt einen Strafzettel bekommen hat",
    ]
})
